# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCiS6GEzB5gdZgAYD_gkZRF28ZY9VzKy

jyotsna chitte
Task 1: Data cleaning
"""

import pandas as pd
import numpy as np

#Importing the dataset
df = pd.read_csv("/content/train.csv")

df

df.head(10)

df.dtypes

df.describe()

df.columns

"""Data Cleaning"""

df.isnull().sum()

int(df["Age"].mean())

# replace the missing values with median
df['Age']=df['Age'].fillna(np.mean(df['Age']))

df.isnull().sum()

df['Embarked'].mode()

df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

df.isnull().sum()

df['Cabin'].value_counts()

df['Cabin'].mode()

df['Cabin'].fillna(df['Cabin'].mode()[0],inplace=True)

df.isnull().sum()

df.corr()

"""thank you"""